### ISSUE TITLE
AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS' - Issue - Just downgrade pillow

### ISSUE THREAD

**Issue by welpdx** [shawnrivers/gif-compressor#2]
![image](https://github.com/shawnrivers/gif-compressor/assets/30542416/ad761ddf-b464-47eb-992f-af7acd31fa3c)

```
Current job: C:\Users\Administrator\Documents\ShareX\Screenshots\2023-12\InsurgencyClient-Win64-Shipping_231203_160101_.gif

Overall progress: 1/1 Started.

Original Info:
  Dimension: 1920 * 1080
  Frames Count: 1208 (14 fps *  80.98 s)
  File Size: 1301621 KB

Traceback (most recent call last):
  File "C:\repos\gif-compressor\win.py", line 262, in <module>
    compressClip(clip_path)
  File "C:\repos\gif-compressor\win.py", line 126, in compressClip
    temp_clip = clip.resize(height=current_dimension)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\moviepy\video\fx\resize.py", line 152, in resize
    newclip = clip.fl_image(fl)
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\moviepy\video\VideoClip.py", line 490, in fl_image
    return self.fl(lambda gf, t: image_func(gf(t)), apply_to)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\moviepy\Clip.py", line 136, in fl
    newclip = self.set_make_frame(lambda t: fun(self.get_frame, t))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<decorator-gen-61>", line 2, in set_make_frame
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\moviepy\decorators.py", line 14, in outplace
    f(newclip, *a, **k)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\moviepy\video\VideoClip.py", line 644, in set_make_frame
    self.size = self.get_frame(0).shape[:2][::-1]
                ^^^^^^^^^^^^^^^^^
  File "<decorator-gen-11>", line 2, in get_frame
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\moviepy\decorators.py", line 89, in wrapper
    return f(*new_a, **new_kw)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\moviepy\Clip.py", line 93, in get_frame
    return self.make_frame(t)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\moviepy\Clip.py", line 136, in <lambda>
    newclip = self.set_make_frame(lambda t: fun(self.get_frame, t))
                                            ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\moviepy\video\VideoClip.py", line 490, in <lambda>
    return self.fl(lambda gf, t: image_func(gf(t)), apply_to)
                                 ^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\moviepy\video\fx\resize.py", line 150, in <lambda>
    fl = lambda pic: resizer(pic.astype('uint8'), newsize)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\moviepy\video\fx\resize.py", line 37, in resizer
    resized_pil = pilim.resize(newsize[::-1], Image.ANTIALIAS)
                                              ^^^^^^^^^^^^^^^
AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'

```

Issue can be remedied by following what is written on 
https://github.com/JaidedAI/EasyOCR/issues/1077

`pip install --force-reinstall -v "Pillow==9.5.0"`

anyways, ty for this repo!

**Comment by scillidan** [comment]
You used a high Python version `3.12`. Try use stable version liked [requirements.txt](https://github.com/shawnrivers/gif-compressor/blob/a8ce5ecfce481ab3cba4576bc2120b41cc19f71a/requirements.txt) say, the `3.9`. It works:

![image](https://github.com/shawnrivers/gif-compressor/assets/19889610/3d4faa93-34a9-4cc8-926d-eb4f1ab3a358)
